# Dependencies
kramdown:
    input: GFM
    syntax_highlighter: rogue
    syntax_highlighter_opts:
        css_class: 'highlight'

# Plugins
plugins_dir: ./_plugins

    # Redirects
gems:
  - jekyll-redirect-from
  - jekyll-scholar
  - ext.rb

# Permalinks
permalink:        pretty

# Reading Files    
include:
  - _pages
  - Gemfile

# Setup
avatar:           'https://raw.githubusercontent.com/san25dec/san25dec.github.io/master/_images/SitePic.jpg'
title:            'Santhosh Kumar'
tagline:          'Personal Website'
description:      '5th year Dual Degree (BTech, MTech integrated), Electrical Engineering Department, IIT Madras'
url: ""             
baseurl:          "/" 
resumelink: "https://github.com/san25dec/san25dec.github.io/raw/master/_files/SanthoshKumarFull.pdf"
author:
  name:           'Santhosh Kumar Ramakrishnan'

footer-links:
  dribbble:
  email: santhoshkumar.25dec@gmail.com
  facebook: obisankenobi
  flickr:
  github: san25dec
  instagram: 
  linkedin: santhosh-kumar-ramakrishnan-548b1150
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

# Useful reference: http://tuxette.nathalievilla.org/?p=1426#more-142
scholar:
  style: ./assets/bibliography/ieee-with-url.csl
  locale: en

  sort_by: year
  order: descending
  bibliography_list_tag: ul

  source: ./_bibliography/
  repository: pdf
  bibliography: references.bib
  bibliography_template: bibtex

  replace_strings: true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

paginate:         5
